# Generated by Django 4.2.3 on 2023-08-10 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30, verbose_name='Адрес')),
                ('close', models.BooleanField(db_index=True, default=False, verbose_name='Закрыто')),
            ],
            options={
                'verbose_name': 'адрес',
                'verbose_name_plural': 'адреса',
                'ordering': ['city', 'address'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20, unique=True, verbose_name='Город')),
                ('close', models.BooleanField(db_index=True, default=False, verbose_name='Нет филиалов')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='Systems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=30, verbose_name='Название')),
                ('description', models.TextField(max_length=600, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='systems/image', verbose_name='Изображение')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='systems/icon', verbose_name='Иконка')),
                ('difficulty_level', models.CharField(choices=[('1', 'Очень легко'), ('2', 'Легко'), ('3', 'Средне'), ('4', 'Сложно'), ('5', 'Очень сложно')], default='1', max_length=1, verbose_name='Сложность')),
            ],
            options={
                'verbose_name': 'система',
                'verbose_name_plural': 'системы',
                'ordering': ['system'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='Название')),
                ('photo', models.ImageField(upload_to='room/photo', verbose_name='Фото')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='room/icon', verbose_name='Иконка')),
                ('close', models.BooleanField(db_index=True, default=False, verbose_name='Закрыта')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dice_app.address', verbose_name='Адрес')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dice_app.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'комната',
                'verbose_name_plural': 'комнаты',
                'ordering': ['city', 'address', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('description', models.TextField(max_length=600, verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='master/photo', verbose_name='Фото')),
                ('on_holiday', models.BooleanField(db_index=True, default=False, verbose_name='В отпуске')),
                ('fired', models.BooleanField(db_index=True, default=False, verbose_name='Уволен')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dice_app.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'мастер',
                'verbose_name_plural': 'мастера',
                'ordering': ['name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('type_game', models.CharField(default='Ваншот', max_length=15, verbose_name='Тип сессии')),
                ('description', models.TextField(max_length=600, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='game/image', verbose_name='Изображение')),
                ('price', models.IntegerField(default=5000, verbose_name='Стоимость')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('time', models.TimeField(verbose_name='Время проведения')),
                ('total_seats', models.IntegerField(default=6, verbose_name='Количество участников')),
                ('filled_seats', models.IntegerField(default=0, verbose_name='Занято мест')),
                ('canceled', models.BooleanField(db_index=True, default=False, verbose_name='Отменено')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dice_app.master', verbose_name='Мастер')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dice_app.room', verbose_name='Место игры')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dice_app.systems', verbose_name='Система')),
            ],
            options={
                'verbose_name': 'игра',
                'verbose_name_plural': 'игры',
                'ordering': ['date', 'time', 'room'],
            },
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dice_app.city', verbose_name='Город'),
        ),
    ]
