# Generated by Django 4.2.3 on 2023-08-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='game',
            name='type_game',
            field=models.CharField(default='Ваншот', max_length=20, verbose_name='Тип сессии'),
        ),
        migrations.AlterField(
            model_name='master',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='systems',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Описание'),
        ),
    ]
