# Generated by Django 4.2.3 on 2023-08-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice_app', '0002_alter_game_description_alter_game_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(max_length=900, verbose_name='Описание'),
        ),
    ]
