# Generated by Django 4.2.3 on 2023-08-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice_app', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatars',
            field=models.ImageField(default='user.png', upload_to='user/avatars'),
        ),
    ]
