# Generated by Django 4.2.3 on 2023-08-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice_app', '0007_alter_profile_avatars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatars',
            field=models.ImageField(default='user/avatars/user.png', upload_to='user/avatars'),
        ),
    ]
