# Generated by Django 4.2.3 on 2023-08-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice_app', '0008_alter_profile_avatars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='profile',
            name='male',
            field=models.CharField(blank=True, choices=[('М', 'мужской'), ('Ж', 'женский')], max_length=20, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Телеграм'),
        ),
    ]
